version: "3.9"

services:
  web:
    image: tdvolgograd/untitled7:latest  # Ваш Docker-образ
    ports:
      - "80:80"  # Проброс порта
    deploy:
      replicas: 3  # Количество реплик
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
      restart_policy:
        condition: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
