

services:
  staging:
    image: tdvolgograd/untitled7:latest
    container_name: untitled7-staging
    ports:
      - "8880:80"  # Exposing port 80 of the container to 8880 on the host
    networks:
      - app-network
    restart: always

  production:
    image: tdvolgograd/untitled7:latest
    container_name: untitled7-production
    ports:
      - "80:80"  # Exposing port 80 of the container to 80 on the host
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
