global:
  scrape_interval: 5s
  external_labels:
    monitor: 'node'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090'] # IP Address of the localhost. Match the port to your container port

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['127.0.0.1:9100'] # IP Address of the localhost

  - job_name: 'untitled7-prod'
    static_configs:
      - targets: ['127.0.0.1:80'] # IP Address of the localhost

  - job_name: 'untitled7-staging'
    static_configs:
      - targets: ['127.0.0.1:8088'] # IP Address of the localhost
